- name: Check MariaDB and Nginx
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check MariaDB
      command: systemctl is-active mariadb
      register: mariadb_status
      failed_when: mariadb_status.stdout != "active"

    - name: Check Nginx
      command: systemctl is-active nginx
      register: nginx_status
      failed_when: nginx_status.stdout != "active"
